default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: vocare_courses_development
test:
  <<: *default
  database: vocare_courses_test
production:
  primary: &primary_production
    <<: *default
    database: vocare_courses_production
    username: vocare
    password: <%= Rails.application.credentials[:database_password] %>
  cache:
    <<: *primary_production
    database: vocare_courses_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: vocare_courses_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: vocare_courses_production_cable
    migrations_paths: db/cable_migrate
